import type { NutrientData } from "./nutrient-types";

const ANVISA = {
  title: "Anvisa — Instrução Normativa nº 75/2020",
  url: "https://www.gov.br/anvisa/en/rules-and-regulations/arquivos/in-75_2020.pdf/%40%40download/file",
  detail: "VDR brasileiros usados na rotulagem nutricional de alimentos em geral.",
};

const NASEM_MACROS = {
  title: "National Academies — DRI de energia, macronutrientes, fibras e aminoácidos",
  url: "https://www.nationalacademies.org/projects/HMD-FNB-18-P-119/publication/10490",
  detail: "Referências para carboidratos, proteínas, gorduras, fibras e ácidos graxos essenciais.",
};

const WHO_DIET = {
  title: "OMS — Healthy diet",
  url: "https://www.who.int/news-room/fact-sheets/detail/healthy-diet",
  detail: "Síntese de recomendações populacionais sobre carboidratos, gorduras, açúcares livres e alimentação saudável.",
};

const NASEM_WATER = {
  title: "National Academies — DRI de água e eletrólitos",
  url: "https://www.nationalacademies.org/projects/HMD-FNB-02-L-03-A/publication/10925",
  detail: "Ingestões adequadas de água total e fundamentos do equilíbrio hídrico.",
};

const CHOLINE_NIH = {
  title: "NIH Office of Dietary Supplements — Choline",
  url: "https://ods.od.nih.gov/factsheets/Choline-HealthProfessional/",
  detail: "Funções, fontes, ingestões de referência, deficiência, excesso e interações da colina.",
};

export const CORE_NUTRIENTS: NutrientData[] = [
  {
    category: "macronutrientes",
    slug: "carboidratos",
    name: "Carboidratos",
    kicker: "Macronutriente · Energia e estrutura",
    accent: "#b5743c",
    deck: "Carboidratos além da divisão entre simples e complexos: glicose, amidos, açúcares, fibras, qualidade da matriz alimentar e números com contexto.",
    lead: "Carboidratos são uma família de moléculas que inclui açúcares, amidos e fibras. Eles fornecem glicose e energia, mas a resposta do organismo depende da estrutura, do alimento, da porção, do preparo e do padrão alimentar — não apenas do nome do nutriente.",
    readingTime: "15 min",
    labelReference: "300 g",
    labelReferenceNote: "VDR brasileiro para o %VD de carboidratos em alimentos em geral; não é meta universal.",
    quickFacts: [
      "Monossacarídeos, dissacarídeos, oligossacarídeos e polissacarídeos têm estruturas diferentes.",
      "O cérebro utiliza glicose, mas o organismo também consegue produzi-la em certas condições.",
      "Grãos, raízes, leguminosas, frutas, leite e vegetais oferecem carboidratos em matrizes distintas.",
      "O VDR brasileiro é 300 g; a RDA norte-americana de 130 g tem outra finalidade.",
      "Açúcares adicionados e carboidratos totais não são sinônimos.",
    ],
    forms: [
      ["Açúcares", "Glicose, frutose, sacarose e lactose são carboidratos de poucas unidades; podem estar naturalmente presentes ou ser adicionados."],
      ["Amidos", "Cadeias de glicose presentes em cereais, tubérculos e leguminosas; gelatinização, resfriamento e moagem mudam a digestão."],
      ["Fibras", "Carboidratos não digeridos pelas enzimas humanas no intestino delgado; têm guia próprio nesta biblioteca."],
      ["Açúcares livres e adicionados", "Categorias regulatórias e de saúde pública; não descrevem todos os açúcares naturais da matriz alimentar."],
    ],
    functions: [
      ["Energia", "Cada grama de carboidrato disponível fornece aproximadamente 4 kcal."],
      ["Glicose sanguínea", "A digestão libera monossacarídeos; insulina e outros hormônios coordenam uso, armazenamento e produção interna."],
      ["Glicogênio", "Fígado e músculos armazenam glicose como glicogênio para diferentes necessidades."],
      ["Preservação de proteína", "Oferta energética adequada reduz a necessidade de usar aminoácidos como combustível."],
    ],
    sources: [
      ["Grãos e raízes", "Arroz, aveia, milho, pães, mandioca, batata e inhame", "Integrais e menos refinados costumam preservar mais fibras e micronutrientes."],
      ["Leguminosas", "Feijões, lentilha, ervilha e grão-de-bico", "Combinam amido, fibras, proteínas e minerais."],
      ["Frutas e vegetais", "Frutas inteiras, hortaliças e vegetais amiláceos", "Água, fibras e estrutura física modulam a experiência alimentar."],
      ["Leite e derivados", "Leite e iogurte natural", "Fornecem lactose junto a proteína e minerais; tolerância individual varia."],
    ],
    physiology: [
      "A velocidade de digestão não depende apenas de ser simples ou complexo. Tamanho de partícula, cocção, fibras, gordura, proteína, acidez e refeição completa alteram a resposta.",
      "Índice glicêmico compara alimentos sob condições padronizadas; carga glicêmica considera também a quantidade. Nenhum dos dois resume sozinho a qualidade global da dieta.",
      "Resfriar certos amidos cozidos pode aumentar parte do amido resistente, mas isso não transforma automaticamente a preparação em alimento de baixo impacto glicêmico.",
    ],
    referenceRows: [
      ["VDR no rótulo brasileiro", "300 g", "Calcular o %VD; não é prescrição individual."],
      ["RDA — adultos", "130 g/dia", "Referência baseada na oferta mínima de glicose ao cérebro; não define a composição ideal da dieta."],
      ["AMDR — adultos", "45%–65% da energia", "Faixa populacional para distribuição de macronutrientes."],
      ["Açúcares livres — OMS", "<10% da energia", "Limite populacional; redução para menos de 5% pode trazer benefício adicional."],
    ],
    inadequacy: [
      "Ingestão muito baixa pode contribuir para baixa oferta energética, cetose, redução do glicogênio e dificuldade de sustentar atividade em algumas pessoas. Esses efeitos dependem do contexto e não diagnosticam deficiência isolada.",
      "O problema mais comum não é a falta de uma molécula específica, mas um padrão alimentar insuficiente em energia, fibras, frutas, vegetais e grãos pouco refinados.",
    ],
    riskGroups: [
      "pessoas com diabetes ou uso de medicamentos que alteram glicemia, que precisam individualizar quantidade e distribuição;",
      "atletas e pessoas com alto volume de exercício, pela demanda de glicogênio e energia;",
      "pessoas com doenças gastrointestinais, intolerâncias ou erros inatos do metabolismo;",
      "crianças, gestantes e idosos com dietas muito restritivas sem acompanhamento.",
    ],
    excess: [
      "Excesso energético crônico, qualquer que seja a fonte, pode favorecer ganho de peso. Bebidas açucaradas e produtos muito refinados facilitam ingestão rápida sem a mesma saciedade de alimentos inteiros.",
      "O rótulo separa açúcares totais de adicionados. Não existe VDR brasileiro para açúcares totais; para adicionados, o VDR é 50 g, que funciona como limite de referência, não meta.",
    ],
    evidenceTitle: "Baixo carboidrato não é sinônimo de alta qualidade",
    evidenceBody: [
      "Uma dieta pode reduzir carboidratos e ainda ser pobre em fibras, vegetais e variedade. Também pode conter carboidratos e ser composta majoritariamente por alimentos minimamente processados.",
      "A decisão útil considera objetivo, sustentabilidade, sintomas, atividade física, condições clínicas e qualidade das substituições — não uma disputa abstrata entre macronutrientes.",
    ],
    practicalChecklist: [
      "Leia carboidratos totais, fibras e açúcares adicionados como informações diferentes.",
      "Observe o alimento inteiro e a porção, não apenas um número isolado.",
      "Evite retirar grupos alimentares por medo sem uma razão clara.",
      "Em diabetes ou hipoglicemia tratada, ajuste com a equipe responsável.",
    ],
    interactions: [
      "Insulina e alguns medicamentos para diabetes tornam quantidade e horário clinicamente relevantes.",
      "Erros inatos, intolerâncias específicas e dietas cetogênicas terapêuticas pertencem ao cuidado especializado.",
      "Fibras e carboidratos fermentáveis podem precisar de ajuste em condições gastrointestinais, sem exclusão automática de longo prazo.",
    ],
    faqs: [
      ["Carboidrato vira açúcar?", "Carboidratos digeríveis são quebrados principalmente em monossacarídeos. Isso não torna arroz, feijão, fruta e refrigerante equivalentes: matriz, nutrientes, fibra, porção e velocidade de consumo diferem."],
      ["Carboidrato à noite engorda?", "O horário isolado não determina ganho de gordura. Balanço energético, padrão total, sono, atividade e contexto metabólico importam mais."],
      ["130 g é a quantidade ideal?", "Não. A RDA de 130 g e o VDR de 300 g têm finalidades diferentes; necessidade e distribuição individuais variam."],
      ["Fruta tem açúcar demais?", "Frutas inteiras oferecem água, fibras e micronutrientes. Recomendações para reduzir açúcares livres não significam evitar frutas inteiras."],
    ],
    references: [ANVISA, NASEM_MACROS, WHO_DIET],
  },
  {
    category: "macronutrientes",
    slug: "proteinas",
    name: "Proteínas",
    kicker: "Macronutriente · Estrutura e renovação",
    accent: "#8f4f42",
    deck: "Proteína com contexto: aminoácidos, síntese e renovação de tecidos, qualidade, digestibilidade, distribuição ao longo do dia e limites da lógica de “quanto mais, melhor”.",
    lead: "Proteínas são cadeias de aminoácidos que formam estruturas, enzimas, transportadores, anticorpos e inúmeros componentes funcionais. O organismo as renova continuamente, por isso quantidade, qualidade, energia total e contexto fisiológico precisam ser lidos em conjunto.",
    readingTime: "16 min",
    labelReference: "75 g",
    labelReferenceNote: "VDR brasileiro para rotulagem; não é a recomendação individual de todas as pessoas.",
    quickFacts: [
      "Nove aminoácidos são indispensáveis na alimentação de adultos.",
      "A RDA de proteína para adultos é 0,8 g/kg/dia em referências norte-americanas.",
      "Qualidade envolve perfil de aminoácidos e digestibilidade, não apenas origem animal ou vegetal.",
      "O VDR brasileiro é 75 g.",
      "Necessidade pode mudar com idade, gestação, atividade, doença e recuperação.",
    ],
    forms: [
      ["Proteínas alimentares", "Misturas de aminoácidos em estruturas próprias de carnes, ovos, leite, leguminosas, grãos, sementes e outros alimentos."],
      ["Aminoácidos indispensáveis", "Não são produzidos em quantidade suficiente; cada um terá guia próprio."],
      ["Aminoácidos dispensáveis", "Podem ser sintetizados pelo organismo em condições usuais."],
      ["Condicionalmente indispensáveis", "Podem se tornar limitantes em crescimento, trauma, doença ou imaturidade metabólica."],
    ],
    functions: [
      ["Estrutura", "Colágeno, queratina, proteínas musculares e matriz extracelular dependem de aminoácidos."],
      ["Enzimas e transporte", "Muitas enzimas, receptores, canais e transportadores são proteínas."],
      ["Defesa e sinalização", "Anticorpos, citocinas e vários hormônios são proteicos."],
      ["Equilíbrio de fluidos", "Proteínas plasmáticas ajudam a transportar moléculas e manter distribuição de líquidos."],
      ["Energia", "Aminoácidos podem ser oxidados, mas essa não é a única nem necessariamente a principal função da proteína."],
    ],
    sources: [
      ["Alimentos animais", "Ovos, leite, carnes, peixes e aves", "Geralmente oferecem todos os aminoácidos indispensáveis em proporções favoráveis."],
      ["Leguminosas", "Feijões, lentilha, grão-de-bico, ervilha e soja", "Fontes relevantes; a soja apresenta perfil particularmente completo."],
      ["Grãos, sementes e oleaginosas", "Arroz, aveia, quinoa, amendoim, sementes e castanhas", "Contribuem e se complementam no conjunto da alimentação."],
      ["Combinações alimentares", "Arroz com feijão e outras misturas", "Complementação não precisa ocorrer na mesma garfada quando a dieta diária é variada."],
    ],
    physiology: [
      "Digestão começa no estômago e continua no intestino delgado; peptidases liberam aminoácidos e pequenos peptídeos para absorção.",
      "O corpo não mantém um depósito exclusivo de proteína comparável ao tecido adiposo ou ao glicogênio. Existe um pool dinâmico de aminoácidos e constante renovação proteica.",
      "Síntese muscular responde a proteína, exercício e energia total. Um alimento ou suplemento isolado não substitui treinamento, sono e dieta suficiente.",
    ],
    referenceRows: [
      ["VDR no rótulo brasileiro", "75 g", "Comparação entre alimentos; não prescrição individual."],
      ["RDA — adultos", "0,8 g/kg/dia", "Referência para adultos saudáveis; corresponde a 56 g para 70 kg."],
      ["AMDR — adultos", "10%–35% da energia", "Faixa de distribuição energética, não obrigação de atingir o topo."],
      ["Gravidez", "1,1 g/kg/dia", "Referência populacional; necessidades variam por fase e condição."],
    ],
    inadequacy: [
      "Ingestão insuficiente pode contribuir para perda de massa magra, pior recuperação, edema em desnutrição grave e prejuízo de crescimento. Geralmente ocorre junto a baixa energia e outras carências.",
      "Albumina baixa não é diagnóstico simples de pouca proteína: inflamação, fígado, rins, hidratação e doença aguda alteram o marcador.",
    ],
    riskGroups: [
      "idosos com baixa ingestão, perda de apetite ou dificuldade de mastigar;",
      "pessoas em insegurança alimentar, dietas muito restritas ou pós-cirurgia bariátrica;",
      "gestantes, crianças, atletas e pessoas em recuperação, com necessidades próprias;",
      "pessoas com doença renal, hepática ou erros do metabolismo, que não devem generalizar metas populares.",
    ],
    excess: [
      "Não existe um UL geral estabelecido para proteína. Isso não significa que qualquer quantidade seja útil ou segura em toda condição clínica.",
      "Ingestões muito altas podem deslocar fibras e outros alimentos, aumentar carga gastrointestinal e complicar o manejo de algumas doenças renais ou metabólicas. A origem e o padrão alimentar também importam.",
    ],
    evidenceTitle: "Qualidade proteica não se resume a “completa” ou “incompleta”",
    evidenceBody: [
      "A pontuação de uma proteína considera o aminoácido limitante e a digestibilidade. Em uma dieta variada, diferentes alimentos contribuem para o pool diário de aminoácidos.",
      "Dietas vegetarianas e veganas podem atender às necessidades quando energia, quantidade, variedade e nutrientes críticos são planejados. O rótulo “vegetal” por si só não garante adequação.",
    ],
    practicalChecklist: [
      "Calcule metas por contexto, não copiando o VDR do rótulo.",
      "Distribua fontes ao longo do dia se isso facilitar ingestão e tolerância.",
      "Considere o alimento completo: fibras, sódio, gorduras e grau de processamento.",
      "Em doença renal ou hepática, não altere proteína sem orientação da equipe.",
    ],
    interactions: [
      "Levodopa compete com aminoácidos pelo transporte; horários podem ser individualizados clinicamente.",
      "Doença renal, fenilcetonúria, homocistinúria e outras condições exigem manejo especializado.",
      "Suplementos proteicos podem trazer açúcares, sódio, estimulantes ou alérgenos além da proteína.",
    ],
    faqs: [
      ["Quanta proteína preciso?", "A RDA de 0,8 g/kg/dia é uma referência para adultos saudáveis, mas idade, atividade, energia, gestação e condições clínicas podem alterar a meta."],
      ["Proteína vegetal é incompleta?", "Algumas fontes têm menor proporção de um aminoácido indispensável, mas variedade e quantidade ao longo do dia podem complementar o perfil."],
      ["Whey é obrigatório para ganhar músculo?", "Não. É uma fonte conveniente, não indispensável. Alimentação, treinamento, energia total e proteína suficiente são o conjunto relevante."],
      ["Proteína demais faz mal aos rins?", "Em doença renal, quantidade pode precisar de ajuste. Em pessoas saudáveis, a pergunta depende da dose e do tempo; ausência de UL não autoriza extremos."],
    ],
    references: [ANVISA, NASEM_MACROS, WHO_DIET],
  },
  {
    category: "macronutrientes",
    slug: "gorduras",
    name: "Gorduras",
    kicker: "Macronutriente · Membranas, energia e transporte",
    accent: "#9a7932",
    deck: "Gorduras sem moralização: triglicerídeos, fosfolipídios, saturação, fontes alimentares, ácidos graxos essenciais e o que realmente muda o risco.",
    lead: "Gorduras alimentares fornecem energia, integram membranas, transportam vitaminas lipossolúveis e oferecem ácidos graxos essenciais. O efeito de uma dieta depende do tipo de gordura, do alimento que a fornece e do que ela substitui.",
    readingTime: "16 min",
    labelReference: "55 g",
    labelReferenceNote: "VDR brasileiro para gorduras totais; não é teto ou meta individual.",
    quickFacts: [
      "Triglicerídeos são a maior parte da gordura alimentar.",
      "Ácido linoleico e alfa-linolênico são essenciais e têm guias próprios.",
      "Saturada, monoinsaturada e poli-insaturada descrevem ligações químicas, não alimentos inteiros.",
      "O VDR brasileiro é 55 g; gorduras saturadas têm VDR de 22 g.",
      "Gordura trans industrial não tem função necessária e deve ser minimizada.",
    ],
    forms: [
      ["Triglicerídeos", "Três ácidos graxos ligados ao glicerol; principal forma da dieta e do armazenamento energético."],
      ["Fosfolipídios", "Componentes de membranas e lipoproteínas; contêm regiões que interagem com água e gordura."],
      ["Esteróis", "Incluem colesterol e fitoesteróis; colesterol alimentar não é ácido graxo."],
      ["Ácidos graxos", "Podem ser saturados, monoinsaturados ou poli-insaturados; cadeia e posição das ligações influenciam propriedades."],
    ],
    functions: [
      ["Energia", "Cada grama fornece cerca de 9 kcal e contribui para saciedade e densidade energética."],
      ["Membranas", "Fosfolipídios e colesterol ajudam a determinar estrutura e fluidez celular."],
      ["Absorção", "Gordura alimentar favorece absorção de vitaminas A, D, E e K e de carotenoides."],
      ["Sinalização", "Ácidos graxos são precursores de moléculas sinalizadoras e modulam expressão gênica."],
      ["Isolamento e proteção", "Tecido adiposo armazena energia, protege órgãos e participa da regulação endócrina."],
    ],
    sources: [
      ["Óleos, sementes e castanhas", "Azeite, canola, linhaça, chia, amendoim e nozes", "Predominam gorduras insaturadas, com perfis diferentes."],
      ["Peixes", "Sardinha, salmão e outros peixes", "Fornecem proteínas e diferentes ácidos graxos, incluindo EPA e DHA em alguns."],
      ["Laticínios e carnes", "Leite, queijo, manteiga e cortes diversos", "Misturam tipos de gordura; teor e matriz variam."],
      ["Ultraprocessados", "Produtos formulados com óleos, gorduras, amidos e açúcares", "O efeito do alimento não pode ser atribuído somente ao tipo de gordura."],
    ],
    physiology: [
      "Bile emulsifica gordura e enzimas pancreáticas liberam ácidos graxos. Micelas aproximam produtos da digestão da mucosa; quilomícrons os transportam após absorção.",
      "Substituir gordura saturada por poli-insaturada tende a produzir efeito metabólico diferente de substituí-la por carboidrato refinado. A palavra-chave é substituição.",
      "Colesterol sanguíneo é regulado por síntese, captação e excreção. Colesterol alimentar influencia pessoas de forma variável e não se confunde com gordura saturada.",
    ],
    referenceRows: [
      ["VDR — gorduras totais", "55 g", "Referência brasileira para %VD."],
      ["VDR — gorduras saturadas", "22 g", "Referência de limite no rótulo, não meta."],
      ["AMDR — adultos", "20%–35% da energia", "Faixa para gordura total."],
      ["OMS — saturadas", "<10% da energia", "Meta populacional; prioriza substituição por insaturadas."],
      ["OMS — trans", "<1% da energia", "Quanto menor a gordura trans industrial, melhor."],
    ],
    inadequacy: [
      "Dietas extremamente pobres em gordura podem dificultar oferta de ácidos graxos essenciais, absorção de vitaminas lipossolúveis e ingestão energética adequada.",
      "Deficiência de ácidos graxos essenciais é rara fora de má absorção grave, nutrição parenteral inadequada ou restrições extremas.",
    ],
    riskGroups: [
      "pessoas com doenças que prejudicam bile, pâncreas ou absorção de gorduras;",
      "crianças pequenas e pessoas com baixa ingestão energética em dietas muito restritas;",
      "pessoas com hipertrigliceridemia, dislipidemias genéticas ou doença cardiovascular;",
      "usuários de medicamentos que reduzem absorção de gordura.",
    ],
    excess: [
      "Por ser energeticamente densa, gordura pode facilitar excesso calórico, mas o efeito depende de porção, alimento e padrão.",
      "Altas ingestões de saturadas e trans, especialmente em substituição a insaturadas, são foco de saúde pública. Isso não exige tratar todo alimento com gordura como equivalente.",
    ],
    evidenceTitle: "O tipo importa — e a substituição também",
    evidenceBody: [
      "Dizer apenas “reduza gordura” esconde diferenças entre azeite, castanhas, peixe, manteiga e produtos ultraprocessados. A matriz alimentar altera saciedade, nutrientes e padrão de consumo.",
      "A melhor pergunta costuma ser: qual gordura, em qual alimento, em que quantidade e no lugar de quê?",
    ],
    practicalChecklist: [
      "Compare gorduras totais, saturadas e trans sem ignorar a porção.",
      "Priorize fontes insaturadas dentro de uma alimentação variada.",
      "Não trate óleos ou manteigas como medicamentos.",
      "Em má absorção ou uso de anticoagulantes, individualize mudanças e suplementos.",
    ],
    interactions: [
      "Orlistate e outros agentes que reduzem absorção de gordura podem alterar vitaminas lipossolúveis.",
      "Óleos de peixe concentrados podem aumentar preocupação com sangramento em doses altas e combinações específicas.",
      "Doenças pancreáticas, biliares ou intestinais mudam digestão e absorção.",
    ],
    faqs: [
      ["Gordura é ruim?", "Não. É um macronutriente necessário. Tipo, fonte, quantidade, substituição e padrão alimentar determinam a leitura útil."],
      ["Azeite pode ser usado para cozinhar?", "Sim, em condições culinárias usuais. Temperatura, tempo e armazenamento influenciam oxidação, mas isso não torna o azeite exclusivo para uso frio."],
      ["Colesterol do alimento vira colesterol no sangue?", "Há influência, mas síntese interna e resposta individual também contam. Gordura saturada e padrão alimentar frequentemente têm papel importante."],
      ["55 g é o máximo por dia?", "Não. É o VDR brasileiro para rotulagem. Necessidade e distribuição dependem da energia e do contexto individual."],
    ],
    references: [ANVISA, NASEM_MACROS, WHO_DIET],
  },
  {
    category: "acidos-graxos",
    slug: "acido-linoleico-omega-6",
    name: "Ácido linoleico (ômega-6)",
    shortName: "Ácido linoleico",
    kicker: "Ácido graxo essencial · Ômega-6",
    accent: "#b18a2e",
    deck: "O principal ômega-6 essencial: membranas, precursores metabólicos, fontes, Ingestão Adequada e por que “inflamatório” é uma simplificação enganosa.",
    lead: "Ácido linoleico é um ácido graxo poli-insaturado ômega-6 que o organismo não sintetiza. Ele precisa vir da alimentação e participa de membranas e da produção de outros lipídios bioativos.",
    readingTime: "12 min",
    labelReference: "Sem VDR geral",
    labelReferenceNote: "A rotulagem brasileira possui critérios para alegações de ômega-6, mas não um %VD geral para ácido linoleico.",
    quickFacts: ["É essencial.", "Óleos vegetais, sementes e castanhas são fontes relevantes.", "Pode ser convertido em ácido araquidônico, mas a conversão é regulada.", "A referência internacional é uma AI, não RDA.", "Reduzir ômega-6 isoladamente não é estratégia universal anti-inflamatória."],
    forms: [["LA 18:2 n-6", "Notação que descreve 18 carbonos, duas duplas ligações e a primeira na posição ômega-6."], ["Ômega-6", "Família que inclui vários ácidos graxos; ácido linoleico não é sinônimo de todos."], ["Ácido araquidônico", "Derivado de cadeia longa obtido também diretamente em alimentos; participa de sinalização."], ["Óleos e alimentos inteiros", "A mesma molécula pode vir de óleo, sementes ou castanhas em matrizes diferentes."]],
    functions: [["Membranas", "Integra fosfolipídios e influencia propriedades de membranas."], ["Pele", "Oferta adequada participa da barreira cutânea e limita perda de água."], ["Sinalização", "Serve de precursor para ácidos graxos e mediadores com ações diversas."], ["Crescimento", "É necessário ao desenvolvimento normal, especialmente em fases de crescimento."]],
    sources: [["Óleos vegetais", "Soja, milho, girassol e cártamo", "Concentração elevada; porção e uso culinário importam."], ["Sementes", "Girassol, gergelim e outras", "Fornecem também fibras e minerais."], ["Oleaginosas", "Nozes, amendoim e castanhas", "Perfil varia por espécie."], ["Alimentos preparados", "Molhos, pães e produtos com óleos", "O alimento completo determina a qualidade global."]],
    physiology: ["É absorvido com outras gorduras e incorporado a quilomícrons.", "Enzimas de dessaturação e elongação convertem parte em derivados, compartilhando etapas com a família ômega-3.", "A produção de mediadores não permite classificar todo ômega-6 como pró-inflamatório; efeitos dependem de substrato, tecido e contexto."],
    referenceRows: [["AI — homens 19–50", "17 g/dia", "Baseada em ingestões observadas em populações saudáveis."], ["AI — mulheres 19–50", "12 g/dia", "Não é ponto de corte diagnóstico."], ["AMDR", "5%–10% da energia", "Faixa populacional para ômega-6."], ["UL", "Não estabelecido", "Não significa benefício ilimitado."]],
    inadequacy: ["Deficiência é rara, mas pode causar pele seca e descamativa, crescimento prejudicado e alterações de cicatrização em contextos graves.", "Costuma aparecer em má absorção intensa, nutrição parenteral inadequada ou restrição extrema de gordura."],
    riskGroups: ["pessoas com má absorção grave de gorduras;", "pessoas dependentes de nutrição artificial sem composição adequada;", "crianças em dietas extremamente restritas;", "pessoas que eliminam quase todas as fontes de gordura por longos períodos."],
    excess: ["Não há UL estabelecido. O excesso energético e o deslocamento de outros ácidos graxos continuam relevantes.", "Produtos ricos em ômega-6 podem ser ultraprocessados, mas isso não torna a molécula isoladamente a causa de todos os efeitos do produto."],
    evidenceTitle: "Ômega-6 não é sinônimo de inflamação",
    evidenceBody: ["Ácido araquidônico origina mediadores com funções pró-resolução e pró-inflamatórias; a biologia não é uma seta única.", "Evidência populacional não sustenta recomendar redução indiscriminada de ácido linoleico quando ele substitui gordura saturada em uma dieta adequada."],
    practicalChecklist: ["Não elimine óleos, sementes e castanhas para “zerar inflamação”.", "Observe variedade e equilíbrio energético.", "Diferencie alimento inteiro de produto formulado.", "Não use cápsulas como substituto automático de fontes alimentares."],
    interactions: ["Má absorção de gordura reduz aproveitamento.", "Dietas terapêuticas e nutrição parenteral exigem composição profissional.", "A avaliação de risco cardiovascular depende do padrão de substituição, não de um único óleo."],
    faqs: [["Ômega-6 causa inflamação?", "Essa frase é simplista. A família participa de mediadores diversos, e ácido linoleico em quantidades alimentares não deve ser classificado isoladamente como inflamatório."], ["Preciso equilibrar ômega-6 e ômega-3 em uma proporção exata?", "Não existe uma proporção universal clinicamente validada para todas as pessoas. Garantir fontes adequadas de ambos costuma ser mais útil."], ["Óleo de soja é fonte?", "Sim, contém ácido linoleico. A decisão culinária também considera uso, quantidade, estabilidade, sabor e padrão total."], ["Existe %VD?", "Não há VDR geral brasileiro para ácido linoleico; referências individuais usam AI e faixas energéticas."]],
    references: [NASEM_MACROS, WHO_DIET, ANVISA],
  },
  {
    category: "acidos-graxos",
    slug: "acido-alfa-linolenico-omega-3",
    name: "Ácido alfa-linolênico (ômega-3)",
    shortName: "Ácido alfa-linolênico",
    kicker: "Ácido graxo essencial · Ômega-3",
    accent: "#477f82",
    deck: "ALA, o ômega-3 essencial de origem vegetal: fontes, conversão limitada em EPA e DHA, ingestões de referência e o que suplementos não resolvem sozinhos.",
    lead: "Ácido alfa-linolênico, ou ALA, é um ácido graxo poli-insaturado ômega-3 essencial. Ele aparece em sementes e óleos vegetais e pode originar pequenas quantidades de EPA e DHA, com conversão variável e geralmente limitada.",
    readingTime: "13 min",
    labelReference: "Sem VDR geral",
    labelReferenceNote: "A legislação brasileira permite alegações sob critérios específicos, mas não fixa %VD geral para ALA.",
    quickFacts: ["ALA é essencial; EPA e DHA têm funções próprias, mas não são classificados da mesma forma em todas as referências.", "Linhaça, chia, nozes e óleo de canola contribuem.", "Conversão em EPA é limitada e em DHA tende a ser ainda menor.", "A referência é AI.", "Ômega-3 não é tratamento universal nem proteção garantida."],
    forms: [["ALA 18:3 n-3", "Ácido graxo de 18 carbonos e três duplas ligações, primeira na posição ômega-3."], ["EPA", "Ácido eicosapentaenoico de cadeia longa; vem de alimentos marinhos e de conversão limitada do ALA."], ["DHA", "Ácido docosa-hexaenoico, concentrado em retina e sistema nervoso; conversão a partir de ALA é baixa."], ["Óleos de algas e peixes", "Fontes de EPA/DHA, não equivalentes a ALA em composição."]],
    functions: [["Membranas", "Integra fosfolipídios e contribui para a disponibilidade de derivados ômega-3."], ["Precursor", "Pode ser alongado e dessaturado em EPA e, em menor extensão, DHA."], ["Energia", "Também pode ser oxidado como combustível."], ["Desenvolvimento", "A família ômega-3 participa do desenvolvimento normal; fases específicas exigem leitura própria de EPA/DHA."]],
    sources: [["Sementes", "Linhaça e chia", "Trituração da linhaça melhora acesso ao conteúdo interno."], ["Oleaginosas", "Nozes", "Fornecem ALA, energia e outros nutrientes."], ["Óleos", "Canola, soja e linhaça", "Teor e estabilidade variam; luz, oxigênio e calor aceleram oxidação."], ["Fortificados", "Alguns alimentos adicionados de ALA", "Verifique forma, quantidade e porção."]],
    physiology: ["Absorção acompanha outras gorduras. Depois, ALA pode ser oxidado ou incorporado a lipídios.", "LA e ALA compartilham enzimas de conversão, mas reduzir uma família não garante aumento clínico previsível da outra.", "Sexo, genética, dieta e estado fisiológico influenciam conversão; por isso, ALA não deve ser tratado como equivalente quantitativo a EPA+DHA."],
    referenceRows: [["AI — homens adultos", "1,6 g/dia", "Referência de ingestão adequada."], ["AI — mulheres adultas", "1,1 g/dia", "Referência populacional."], ["AI — gravidez", "1,4 g/dia", "Não substitui discussão específica de DHA."], ["AI — lactação", "1,3 g/dia", "Referência populacional."], ["UL", "Não estabelecido", "Não é licença para altas doses de suplementos."]],
    inadequacy: ["Deficiência isolada é rara e geralmente aparece com privação global de ácidos graxos essenciais.", "Pode envolver alterações de pele, crescimento e função neurológica em quadros graves, sem sinais exclusivos."],
    riskGroups: ["pessoas com má absorção de gorduras;", "pessoas em dietas extremamente restritas sem sementes, óleos ou outras fontes;", "gestantes e lactantes que precisam discutir também EPA/DHA;", "pessoas dependentes de nutrição artificial."],
    excess: ["Não há UL para ALA. Óleos continuam densos em energia e suscetíveis à oxidação.", "Riscos de sangramento discutidos para altas doses de EPA/DHA não podem ser automaticamente transferidos ao ALA alimentar."],
    evidenceTitle: "ALA não é uma dose vegetal de óleo de peixe",
    evidenceBody: ["ALA, EPA e DHA pertencem à mesma família, mas não são intercambiáveis. A conversão humana limita equivalências diretas.", "Uma alimentação pode combinar fontes vegetais de ALA com fontes de EPA/DHA conforme preferências, fase da vida e orientação adequada."],
    practicalChecklist: ["Use linhaça triturada ou chia dentro de porções alimentares.", "Armazene óleos sensíveis longe de luz e calor.", "Leia se o rótulo declara ALA, EPA, DHA ou apenas “ômega-3”.", "Em gestação ou anticoagulação, discuta suplementos com profissional habilitado."],
    interactions: ["Má absorção reduz aproveitamento.", "Suplementos concentrados podem trazer outros ômega-3 e ingredientes.", "Anticoagulantes e cirurgias exigem atenção sobretudo com doses altas de EPA/DHA."],
    faqs: [["Linhaça substitui peixe?", "Fornece ALA; peixes gordurosos fornecem EPA e DHA. São fontes diferentes, não equivalentes automáticos."], ["Chia precisa ser triturada?", "A semente hidratada é acessível, mas trituração pode aumentar a liberação de lipídios; a linhaça inteira frequentemente atravessa menos rompida."], ["ALA vira DHA?", "Pode, mas a conversão é baixa e variável. Não use uma equivalência fixa improvisada."], ["Existe %VD?", "Não há VDR geral brasileiro para ALA; referências individuais usam AI."]],
    references: [NASEM_MACROS, WHO_DIET, ANVISA],
  },
  {
    category: "outros-nutrientes",
    slug: "agua",
    name: "Água",
    kicker: "Nutriente essencial · Equilíbrio hídrico",
    accent: "#2f7896",
    deck: "Hidratação sem a regra rígida dos oito copos: água total, sede, urina, perdas, clima, exercício, hiponatremia e situações em que beber mais também pode ser perigoso.",
    lead: "Água é o maior componente do corpo e meio de reações, transporte e controle térmico. A necessidade muda diariamente com clima, tamanho corporal, alimentação, atividade, febre, gestação, lactação e condições clínicas.",
    readingTime: "14 min",
    labelReference: "Sem VDR geral",
    labelReferenceNote: "Não existe %VD brasileiro geral para água; referências usam ingestão adequada de água total.",
    quickFacts: ["Água total inclui bebidas e a água dos alimentos.", "Sede funciona bem para muitas pessoas saudáveis, mas não em todas as situações.", "Urina clara o tempo todo não é meta universal.", "AI: 3,7 L/dia para homens e 2,7 L/dia para mulheres, incluindo alimentos.", "Excesso rápido pode causar hiponatremia."],
    forms: [["Água de bebidas", "Água potável, leite, café, chá e outras bebidas contribuem em proporções diferentes."], ["Água dos alimentos", "Frutas, hortaliças, sopas, leite e preparações fornecem parte importante."], ["Água metabólica", "Pequena quantidade é produzida na oxidação de nutrientes."], ["Soluções de reidratação", "Têm proporções específicas de água, glicose e eletrólitos; não são equivalentes a bebidas esportivas comuns."]],
    functions: [["Transporte", "Compõe sangue e fluidos que distribuem nutrientes e removem resíduos."], ["Temperatura", "Evaporação do suor ajuda a dissipar calor."], ["Reações", "É solvente e participa de reações bioquímicas."], ["Volume celular", "Osmolalidade e eletrólitos mantêm distribuição adequada entre compartimentos."], ["Digestão e excreção", "Integra secreções, fezes e urina."]],
    sources: [["Água potável", "Água da rede tratada, filtrada ou engarrafada", "Qualidade sanitária vem antes de mineralização de marketing."], ["Bebidas", "Leite, café, chá e outras", "Cafeína moderada não anula toda a água da bebida."], ["Alimentos", "Frutas, vegetais, feijões e sopas", "Contribuição varia com o padrão alimentar."], ["Exercício prolongado", "Água e, em alguns cenários, eletrólitos", "Estratégia depende de duração, calor e perdas individuais."]],
    physiology: ["Osmorreceptores e hormônios como vasopressina regulam sede e concentração da urina.", "Rins ajustam excreção dentro de limites. Beber grandes volumes rapidamente pode superar a capacidade de eliminar água livre.", "Durante exercício, peso antes/depois e condições ambientais podem ajudar a estimar perdas, mas não devem incentivar reposição acima do peso perdido."],
    referenceRows: [["AI — homens adultos", "3,7 L/dia", "Água total de bebidas e alimentos."], ["AI — mulheres adultas", "2,7 L/dia", "Água total, não apenas copos."], ["AI — gravidez", "+0,3 L/dia", "Acréscimo médio à referência feminina."], ["AI — lactação", "+1,1 L/dia", "Acréscimo médio; sede e produção de leite variam."], ["UL", "Não estabelecido", "Capacidade renal e velocidade de ingestão limitam segurança."]],
    inadequacy: ["Desidratação pode causar sede, boca seca, menor volume urinário, tontura e queda de desempenho; sinais não são específicos.", "Confusão, sonolência intensa, incapacidade de beber, vômitos persistentes ou sinais de choque exigem avaliação rápida."],
    riskGroups: ["idosos, crianças pequenas e pessoas dependentes para acesso a líquidos;", "pessoas com febre, vômitos, diarreia ou perdas elevadas;", "trabalhadores e atletas expostos a calor;", "pessoas com doenças renais, cardíacas, hepáticas ou endócrinas, que podem precisar restringir ou ajustar líquidos."],
    excess: ["Ingestão excessiva em pouco tempo pode diluir o sódio sanguíneo e causar náusea, cefaleia, confusão, convulsões e risco de morte.", "Hiponatremia também pode ocorrer durante provas prolongadas quando a pessoa bebe mais do que perde, especialmente só água."],
    evidenceTitle: "“Dois litros para todos” é uma regra de comunicação, não uma necessidade universal",
    evidenceBody: ["A AI de água total inclui alimentos e deriva de ingestões observadas. Clima, dieta e corpo mudam a necessidade real.", "Uma orientação prática para adultos saudáveis combina sede, disponibilidade de água, cor da urina como pista imperfeita e atenção a perdas — sem obsessão por um número único."],
    practicalChecklist: ["Tenha água acessível e beba regularmente conforme sede e rotina.", "Aumente atenção em calor, febre, exercício ou perdas gastrointestinais.", "Não force litros rapidamente para “desintoxicar”.", "Se recebeu restrição de líquidos, siga a equipe assistente."],
    interactions: ["Diuréticos, lítio e medicamentos que alteram vasopressina ou sódio mudam o risco.", "Doença renal, cardíaca, hepática e insuficiência adrenal exigem individualização.", "Soluções de reidratação oral são formulações específicas para perdas gastrointestinais; preparo incorreto pode ser perigoso."],
    faqs: [["Preciso beber oito copos?", "Não é uma regra universal. Necessidade inclui água dos alimentos e varia com clima, corpo, atividade e saúde."], ["Café desidrata?", "Cafeína pode aumentar diurese aguda em algumas condições, mas bebidas cafeinadas usuais ainda contribuem para água total."], ["Urina transparente é melhor?", "Não necessariamente. Transparência constante pode refletir excesso; amarelo-claro é uma pista comum, mas medicamentos e alimentos alteram cor."], ["Água demais faz mal?", "Sim. Grande volume em pouco tempo pode causar hiponatremia, especialmente em exercício prolongado ou algumas doenças."]],
    references: [NASEM_WATER, WHO_DIET],
  },
  {
    category: "outros-nutrientes",
    slug: "fibras-alimentares",
    name: "Fibras alimentares",
    kicker: "Componente dietético · Estrutura e fermentação",
    accent: "#5c7d4b",
    deck: "Fibras além de “solúvel e insolúvel”: viscosidade, fermentação, microbiota, trânsito intestinal, fontes, aumento gradual e limites de suplementos.",
    lead: "Fibras alimentares são carboidratos não digeridos pelas enzimas humanas no intestino delgado. Algumas formam géis, outras aumentam volume e várias são fermentadas pela microbiota — propriedades mais úteis que uma classificação única.",
    readingTime: "15 min",
    labelReference: "25 g",
    labelReferenceNote: "VDR brasileiro para fibra alimentar no %VD de alimentos em geral.",
    quickFacts: ["Fibra alimentar e fibra funcional têm definições técnicas.", "Viscosidade e fermentabilidade ajudam a prever efeitos.", "Feijões, frutas, vegetais, grãos integrais, sementes e castanhas contribuem.", "O VDR brasileiro é 25 g.", "Aumentar rápido sem água suficiente pode piorar sintomas."],
    forms: [["Fibras viscosas", "Formam géis e podem reduzir velocidade de esvaziamento e absorção; psyllium é exemplo."], ["Fibras fermentáveis", "Servem de substrato para microrganismos e geram ácidos graxos de cadeia curta, além de gases."], ["Fibras pouco fermentáveis", "Aumentam massa fecal e podem acelerar trânsito em algumas pessoas."], ["Amido resistente", "Escapa parcialmente da digestão e pode ser fermentado no cólon."],
    ],
    functions: [["Trânsito intestinal", "Alguns tipos aumentam volume e maciez das fezes."], ["Glicemia", "Fibras viscosas podem reduzir a velocidade de absorção de glicose."], ["Colesterol", "Determinadas fibras viscosas aumentam excreção de ácidos biliares e podem reduzir LDL."], ["Microbiota", "Fibras fermentáveis alimentam comunidades microbianas, com respostas individuais."], ["Saciedade", "Volume, mastigação e matriz alimentar podem contribuir, sem efeito uniforme."]],
    sources: [["Leguminosas", "Feijões, lentilha, ervilha e grão-de-bico", "Combinam fibras fermentáveis e amido resistente."], ["Grãos integrais", "Aveia, cevada, centeio, milho e arroz integral", "O tipo e o processamento mudam a estrutura."], ["Frutas e vegetais", "Frutas inteiras, folhas, raízes e crucíferos", "Variedade oferece diferentes fibras e água."], ["Sementes e castanhas", "Chia, linhaça, amendoim e oleaginosas", "Contribuem com fibras, gorduras e minerais."]],
    physiology: ["Fibras chegam ao cólon em quantidades diferentes. Fermentação produz acetato, propionato e butirato, além de gases.", "A resposta depende do tipo, dose, adaptação da microbiota, motilidade, água e condição gastrointestinal.", "“Prebiótico” exige benefício demonstrado ao hospedeiro; nem toda fibra fermentável pode ser chamada automaticamente assim."],
    referenceRows: [["VDR no rótulo brasileiro", "25 g", "Referência para %VD."], ["AI — homens 19–50", "38 g/dia", "Baseada em 14 g por 1.000 kcal."], ["AI — mulheres 19–50", "25 g/dia", "Referência populacional."], ["AI — homens 51+", "30 g/dia", "Ajuste associado à menor ingestão energética média."], ["AI — mulheres 51+", "21 g/dia", "Não é teto."]],
    inadequacy: ["Baixa ingestão é comum e pode contribuir para constipação e menor variedade de substratos para a microbiota, mas evacuação depende de múltiplos fatores.", "Constipação nova, sangramento, perda de peso ou dor importante não deve ser tratada apenas aumentando fibra."],
    riskGroups: ["pessoas com dietas pobres em vegetais, leguminosas e grãos integrais;", "pessoas com baixa ingestão de líquidos ou mobilidade reduzida;", "pessoas com estenose, gastroparesia, crises inflamatórias ou pós-operatório, que podem precisar ajustar tipo e quantidade;", "usuários de medicamentos que alteram trânsito intestinal."],
    excess: ["Aumento abrupto pode causar gases, distensão, dor e alteração do hábito intestinal.", "Suplementos concentrados podem reduzir absorção de medicamentos quando tomados juntos e, sem líquido suficiente, aumentar risco de obstrução em pessoas vulneráveis."],
    evidenceTitle: "Nem toda fibra faz a mesma coisa",
    evidenceBody: ["Farelo de trigo, beta-glucanas, inulina e psyllium têm propriedades distintas. Resultados de um tipo não devem ser transferidos para todos.", "Variedade de alimentos costuma oferecer uma combinação mais ampla do que buscar um único pó para resolver toda a alimentação."],
    practicalChecklist: ["Aumente gradualmente.", "Associe líquidos adequados conforme tolerância e condição clínica.", "Varie leguminosas, frutas, vegetais e grãos.", "Separe suplementos de medicamentos conforme orientação do rótulo ou profissional."],
    interactions: ["Psyllium e outras fibras podem alterar absorção de medicamentos e devem ser espaçados conforme orientação.", "Estenoses, disfagia e certas doenças intestinais mudam a segurança.", "Dietas low-FODMAP são intervenções temporárias e estruturadas, não justificativa para excluir fibras indefinidamente."],
    faqs: [["Fibra solúvel é melhor?", "Não existe melhor universal. Viscosidade, fermentabilidade e objetivo importam; uma dieta variada combina propriedades."], ["Suco tem a mesma fibra da fruta?", "Geralmente não. Extração e coagem reduzem estrutura e parte da fibra; mesmo liquidificar muda a matriz."], ["Fibra prende ou solta o intestino?", "Depende do tipo, dose, água e causa do sintoma. Psyllium pode ajudar a normalizar consistência; farelos muito ásperos podem piorar algumas pessoas."], ["25 g é suficiente para todos?", "É o VDR brasileiro e também a AI de mulheres adultas mais jovens, mas necessidades e tolerância variam."]],
    references: [ANVISA, NASEM_MACROS, WHO_DIET],
  },
  {
    category: "outros-nutrientes",
    slug: "colina",
    name: "Colina",
    kicker: "Nutriente essencial · Membranas e metilação",
    accent: "#6b5d8e",
    deck: "Colina com contexto: fosfatidilcolina, acetilcolina, betaína, fígado, gestação, fontes e por que um VDR alto não é convite para megadoses.",
    lead: "Colina é um nutriente essencial: o fígado produz alguma quantidade, mas não o suficiente para todas as necessidades. Ela integra membranas, transporte de lipídios, acetilcolina e metabolismo de unidades de um carbono.",
    readingTime: "14 min",
    labelReference: "550 mg",
    labelReferenceNote: "VDR brasileiro de rotulagem; referências individuais diferem por sexo e fase da vida.",
    quickFacts: ["Não é oficialmente uma vitamina B, embora apareça próxima ao complexo B.", "O organismo sintetiza parte, mas a dieta continua necessária.", "Ovos, carnes, peixes, soja e crucíferos contribuem.", "O VDR brasileiro é 550 mg.", "O UL adulto é 3.500 mg/dia."],
    forms: [["Fosfatidilcolina", "Principal fosfolipídio de membranas e forma importante nos alimentos."], ["Colina livre", "Forma solúvel usada diretamente ou convertida em outros compostos."], ["Acetilcolina", "Neurotransmissor produzido a partir de colina e acetil-CoA."], ["Betaína", "Produto de oxidação da colina que doa grupos metil no metabolismo da homocisteína."],
    ],
    functions: [["Membranas", "Fosfatidilcolina e esfingomielina ajudam a estruturar células."], ["Fígado", "É necessária para formar lipoproteínas que exportam triglicerídeos do fígado."], ["Neurotransmissão", "Acetilcolina participa de memória, atenção, controle muscular e funções autonômicas."], ["Metilação", "Betaína contribui para remetilar homocisteína em metionina."], ["Desenvolvimento", "A demanda aumenta em gestação e lactação; isso não define dose automática de suplemento."]],
    sources: [["Ovos", "Principalmente gema", "Fonte concentrada de fosfatidilcolina."], ["Carnes e peixes", "Fígado, carnes, frango, bacalhau e salmão", "Teor varia; fígado também concentra vitamina A."], ["Vegetais", "Soja, feijões, brócolis e couve-flor", "Contribuem dentro de dietas vegetais variadas."], ["Leite, grãos e sementes", "Leite, trigo integral, quinoa, amendoim", "Fontes complementares."]],
    physiology: ["Formas alimentares são absorvidas e distribuídas como colina livre ou fosfolipídios.", "O fígado sintetiza fosfatidilcolina pela via PEMT, influenciada por estrogênio e disponibilidade de grupos metil.", "A microbiota pode converter parte da colina em trimetilamina, depois oxidada a TMAO. Associação com risco cardiovascular não prova que retirar alimentos com colina melhore desfechos."],
    referenceRows: [["VDR no rótulo brasileiro", "550 mg", "Referência para %VD."], ["AI — homens adultos", "550 mg/dia", "Ingestão Adequada."], ["AI — mulheres adultas", "425 mg/dia", "Referência populacional."], ["AI — gravidez", "450 mg/dia", "Demanda de desenvolvimento."], ["AI — lactação", "550 mg/dia", "Perdas pelo leite elevam a referência."], ["UL — adultos", "3.500 mg/dia", "Baseado em hipotensão, odor corporal e efeitos colinérgicos."]],
    inadequacy: ["Deficiência experimental pode causar acúmulo de gordura no fígado e dano muscular. Suscetibilidade varia com genética, sexo e disponibilidade de folato e metionina.", "Fígado gorduroso tem muitas causas; não deve ser autodiagnosticado como falta de colina."],
    riskGroups: ["gestantes e lactantes com alimentação pouco variada;", "pessoas em nutrição parenteral inadequadamente formulada;", "pessoas com variantes genéticas que aumentam necessidade;", "pessoas que excluem ovos, carnes e soja sem planejar fontes alternativas."],
    excess: ["Altas doses podem causar odor corporal semelhante a peixe, vômitos, suor e salivação excessivos, pressão baixa e toxicidade hepática.", "O UL soma alimentos e suplementos. Superá-lo não significa benefício cognitivo maior."],
    evidenceTitle: "Colina, cérebro e TMAO: duas simplificações a evitar",
    evidenceBody: ["Colina é necessária à acetilcolina, mas suplementos não demonstram melhorar memória de todas as pessoas saudáveis.", "TMAO se associa a risco em estudos observacionais, porém função renal, microbiota, peixe e doença alteram níveis. Isso não justifica eliminar fontes nutritivas isoladamente."],
    practicalChecklist: ["Observe variedade de fontes, especialmente na gestação.", "Some colina de múltiplos suplementos.", "Não use sintomas vagos para diagnosticar deficiência.", "Não ultrapasse altas doses visando foco ou memória sem avaliação."],
    interactions: ["Folato, B12, B6, riboflavina e metionina se conectam ao metabolismo de um carbono.", "Atropina e outros agentes anticolinérgicos têm farmacologia própria; suplementos não os neutralizam.", "Doença hepática ou renal exige avaliação contextual."],
    faqs: [["Colina é vitamina B?", "É um nutriente essencial semelhante em alguns aspectos ao complexo B, mas não é classificada como uma das oito vitaminas B reconhecidas."], ["Ovo tem colina?", "Sim, principalmente a gema. A contribuição depende do tamanho e da alimentação completa."], ["Colina melhora memória?", "Ela é necessária à neurotransmissão, mas necessidade fisiológica não prova benefício de doses extras em pessoas adequadas."], ["550 mg é a meta de todas as mulheres?", "Não. É o VDR brasileiro e a AI de homens e lactantes; a AI para mulheres adultas é 425 mg."]],
    references: [ANVISA, CHOLINE_NIH, NASEM_MACROS],
  },
];

