const SITE_URL = "https://www.cleversouza.com";

const routeImages: Record<string, string> = {
  "/": "inicio",
  "/sobre": "sobre",
  "/contato": "contato",
  "/aviso-de-saude": "aviso-de-saude",
  "/politica-de-privacidade": "politica-de-privacidade",
  "/termos-de-uso": "termos-de-uso",
  "/massoterapia": "massoterapia",
  "/massoterapia/quick-massage-corporativo": "quick-massage-corporativo",
  "/massoterapia-curitiba": "massoterapia-curitiba",
  "/servicos": "servicos",
  "/conteudos": "conteudos",
  "/massoterapia/conteudo": "massoterapia-conteudo",
  "/nutricao": "nutricao",
  "/ia": "ia",
  "/ia/engenharia-de-prompt": "engenharia-de-prompt",
  "/ia/context-engineering": "context-engineering",
  "/ia/pesquisa-com-ia": "pesquisa-com-ia",
  "/ia/ia-com-arquivos": "ia-com-arquivos",
  "/ia/prompts-para-imagens": "prompts-para-imagens",
  "/ia/videos-curtos": "videos-curtos",
  "/ia/avaliacao-de-respostas-de-ia": "avaliacao-de-respostas-de-ia",
  "/ia/napoleon-hill": "napoleon-hill",
  "/nutricao/vitaminas": "vitaminas",
  "/nutricao/vitaminas/vitamina-a": "vitamina-a",
  "/nutricao/vitaminas/vitamina-b1": "vitamina-b1",
  "/nutricao/vitaminas/vitamina-b2": "vitamina-b2",
  "/nutricao/vitaminas/vitamina-b3": "vitamina-b3",
  "/nutricao/vitaminas/vitamina-b5": "vitamina-b5",
  "/nutricao/vitaminas/vitamina-b6": "vitamina-b6",
  "/nutricao/vitaminas/vitamina-b7": "vitamina-b7",
  "/nutricao/vitaminas/vitamina-b9": "vitamina-b9",
  "/nutricao/vitaminas/vitamina-b12": "vitamina-b12",
  "/nutricao/vitaminas/vitamina-c": "vitamina-c",
  "/nutricao/vitaminas/vitamina-d": "vitamina-d",
  "/nutricao/vitaminas/vitamina-e": "vitamina-e",
  "/nutricao/vitaminas/vitamina-k": "vitamina-k",
  "/nutricao/macronutrientes": "macronutrientes",
  "/nutricao/macronutrientes/carboidratos": "carboidratos",
  "/nutricao/macronutrientes/proteinas": "proteinas",
  "/nutricao/macronutrientes/gorduras": "gorduras",
  "/nutricao/minerais": "minerais",
  "/nutricao/minerais/calcio": "calcio",
  "/nutricao/minerais/fosforo": "fosforo",
  "/nutricao/minerais/magnesio": "magnesio",
  "/nutricao/minerais/sodio": "sodio",
  "/nutricao/minerais/potassio": "potassio",
  "/nutricao/minerais/cloreto": "cloreto",
  "/nutricao/minerais/ferro": "ferro",
  "/nutricao/minerais/zinco": "zinco",
  "/nutricao/minerais/cobre": "cobre",
  "/nutricao/minerais/manganes": "manganes",
  "/nutricao/minerais/iodo": "iodo",
  "/nutricao/minerais/selenio": "selenio",
  "/nutricao/minerais/molibdenio": "molibdenio",
  "/nutricao/minerais/cromo": "cromo",
  "/nutricao/minerais/fluor": "fluor",
  "/nutricao/aminoacidos": "aminoacidos",
  "/nutricao/aminoacidos/histidina": "histidina",
  "/nutricao/aminoacidos/isoleucina": "isoleucina",
  "/nutricao/aminoacidos/leucina": "leucina",
  "/nutricao/aminoacidos/lisina": "lisina",
  "/nutricao/aminoacidos/metionina": "metionina",
  "/nutricao/aminoacidos/fenilalanina": "fenilalanina",
  "/nutricao/aminoacidos/treonina": "treonina",
  "/nutricao/aminoacidos/triptofano": "triptofano",
  "/nutricao/aminoacidos/valina": "valina",
  "/nutricao/acidos-graxos": "acidos-graxos",
  "/nutricao/acidos-graxos/acido-linoleico-omega-6": "acido-linoleico-omega-6",
  "/nutricao/acidos-graxos/acido-alfa-linolenico-omega-3": "acido-alfa-linolenico-omega-3",
  "/nutricao/outros-nutrientes": "outros-nutrientes",
  "/nutricao/outros-nutrientes/agua": "agua",
  "/nutricao/outros-nutrientes/fibras-alimentares": "fibras-alimentares",
  "/nutricao/outros-nutrientes/colina": "colina",
  "/conteudos/o-que-e-massoterapia": "conteudos-o-que-e-massoterapia",
  "/conteudos/primeira-sessao-de-massoterapia": "conteudos-primeira-sessao-de-massoterapia",
  "/conteudos/massagem-relaxante-e-terapeutica": "conteudos-massagem-relaxante-e-terapeutica",
  "/conteudos/cuidados-e-contraindicacoes": "conteudos-cuidados-e-contraindicacoes",
  "/conteudos/como-escolher-massoterapeuta-curitiba": "conteudos-como-escolher-massoterapeuta-curitiba",
};

const techniqueImages: Record<string, string> = {
  "massagem-relaxante": "massagem-relaxante",
  shiatsu: "shiatsu",
  "tui-na": "tui-na",
  "reflexologia-podal": "reflexologia-podal",
  "thai-massage": "thai-massage",
  "quick-massage": "quick-massage",
};

export function socialImageUrl(name: string) {
  return `${SITE_URL}/social/${name}.png`;
}

export function routeSocialImage(path: string) {
  return socialImageUrl(routeImages[path] ?? "inicio");
}

export function techniqueSocialImage(imageStem: string) {
  return socialImageUrl(techniqueImages[imageStem] ?? "massoterapia-conteudo");
}
